### ISSUE TITLE
How to send a newsletter with mailjet's Rest Java API?

### ISSUE THREAD

**Issue by iisrail** [mailjet/mailjet-apiv3-java#10]
I see in v3 reference in mailJet's site http://dev.mailjet.com/email-api/v3/newsletter-send/ there is the following example:

    curl -s -X POST \
    --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
    https://api.mailjet.com/v3/REST/newsletter/:id/send
but I can't find in all your code any example how it should be done with mailjet Java API https://github.com/mailjet/mailjet-apiv3-java?

The same question I have about other parameters that used after newsletter/:id/ such as:
detailcontent, schedule. I suppose that in the case I'll grasp how to work with one of them the handling of others will be the same.

**Comment by Gormador** [comment]
Hi @iisrail,

I'm really sorry for the lack of response from our part, this issue seems to have been lost in other work...

Unfortunately actions on resources like `newsletter/:ID/send` aren't implemented in the java wrapper. It is in our pipeline but I am not able to give you any ETA for the related release...


My apologies again for the distinct lack of reply.
Gaëtan

**Comment by loriepisicchio** [comment]
+1!
