### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching api.mailjet.com found

### ISSUE THREAD

**Issue by icodetlrn** [mailjet/mailjet-apiv3-java#126]
While using the latest SDK of Mailjet using JDK 11 getting following error while sending email
j
avax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching api.mailjet.com found

**Comment by echle** [comment]
Hi,

we had the same issue and found out, it is due to a misconfiguration of the certificate. Instead of *.mailjet.com it is isseud to *.eu.mailjet.com.

Luckily "api.eu.mailjet.com" also works as baseUrl for the api.

Working with the following ClientOptions we had no problems anymore:

`new ClientOptions("v3.1", "https://api.eu.mailjet.com");`

I hope this helps some of you!

**Comment by goacoustic** [comment]
@icodetlrn Hi! 
Seems like the certificate was already fixed, I checked that it works fine.

I'm closing this as outdated, please, open the new issue in case of any other problems.
