### ISSUE TITLE
Contactdata may be broken

### ISSUE THREAD

**Issue by travismcchesney** [mailjet/mailjet-apiv3-java#7]
Hello,

I ran across an issue while trying to retrieve a Contactdata object.  The exception I'm seeing is: `java.lang.IllegalStateException: Expected a long but was BEGIN_OBJECT at line 1 column 56`

I dug around the code a little, and it seems as though the Contactdata object (`Contactdata.java`) is defining the `Data` field this way: `private java.util.List<Long> Data`.  However, the payload being returned to the wrapper is: 
```json
{
  "Count": 1, 
  "Data": [
    {
      "ContactID": 1, 
      "Data": [
        {
          "Name": "foo", 
          "Value": "Bar"
        }
      ], 
      "ID": 1
    }
  ], 
  "Total": 1
}
```

Clearly the `Data` field is not just a list of `Long`s.

My original call looks like: 
```
Contactdata cd = this.client.createCall(Contactdata.Get).identifiedBy(ContactdataProperty.ID,
                        parseLong(ID)).execute();
```

Any help figuring out what I might be doing wrong would be much appreciated.
I'm using the 1.0.5 distribution.

**Comment by hristo-todorov** [comment]
Hi @travismcchesney ,

Thanks for the post. There was an issue in the java wrapper and was fixed in release 1.0.7. As there is a newer one you can use it too. The last release is 1.0.8 and could be found at https://github.com/mailjet/mailjet-apiv3-java/tree/master/dists/mailjet-wrapper-1.0.8

I hope that helps. For more questions don't hesitate to ask.

Cheers!
