### ISSUE TITLE
Send Pdf File Attachement ?

### ISSUE THREAD

**Issue by chihebnabil** [mailjet/mailjet-apiv3-java#78]
Hi, 

Can any one help me in  sending pdf file attachement ? according to mailjet api the content must be a 64bit encoded string 
- Must i use a pdf library such as iText  to read the file?
- Is there an easy  way to do it ? 

Regards

**Comment by Zhivko-Mailjet** [comment]
Hi @chihebnabil 
You should pass the content of the attachment as base64 encoded string indeed. You can try reading the file as a stream of bytes and then convert it to base64. I was able to find similar scenario with a solution:
https://stackoverflow.com/questions/2418485/how-do-i-convert-a-byte-array-to-base64-in-java

I hope you understand that your question is related to the Java implementation, rather than related to the Mailjet wrapper, but I believe that the above-mentioned suggestion will help.

**Comment by chihebnabil** [comment]
Thanks @Zhivko-Mailjet  for your help  i did this and it worked fine 
```java
                  File fff = new File("path of file");
		  FileInputStream fileInputStream = new FileInputStream(fff);
		  int byteLength=(int) fff.length(); 
		  byte[] filecontent = new byte[byteLength];
		  fileInputStream.read(filecontent,0,byteLength);
		 byte[] encoded = Base64.getEncoder().encode(filecontent);
```

**Comment by chihebnabil** [comment]
Thanks @Zhivko-Mailjet  i did this and it works fine
```java
                  File fff = new File("my pdf file pathf");
		  FileInputStream fileInputStream = new FileInputStream(fff);
		  int byteLength=(int) fff.length(); //bytecount of the file-content
		  byte[] filecontent = new byte[byteLength];
		  fileInputStream.read(filecontent,0,byteLength);
		  byte[] encoded = Base64.getEncoder().encode(filecontent);
```

**Comment by Zhivko-Mailjet** [comment]
Glad I was able to help. I'm closing the issue. Have a great day!
